{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "immich-server.name" . }}
  labels:
      {{- include "immich-server.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- .Values.httpRoute.parentRefs | toYaml | nindent 4 }}
  hostnames:
    {{- .Values.httpRoute.hostnames | toYaml | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "immich-server.name" . }}
          port: {{ .Values.server.service.port }}
{{- end -}}
