{{- if not .Values.common.postgres.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}-postgres
  labels:
    {{- include "immich.commonLabels" . | nindent 4 }}
type: Opaque
data:
  username: "{{ .Values.common.postgres.createSecret.username | b64enc }}"
  password: "{{ .Values.common.postgres.createSecret.password | b64enc }}"
{{- end }}
---
{{- if not .Values.common.redis.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}-redis
  labels:
    {{- include "immich.commonLabels" . | nindent 4 }}
type: Opaque
data:
  password: "{{ .Values.common.redis.createSecret.password | b64enc }}"
{{- end }}
